// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArKWnJldG8mJMXADIReb2tG6KVs-M8Gbg',
    appId: '1:610530270497:web:cd0122a905671021e07260',
    messagingSenderId: '610530270497',
    projectId: 'to-do-app-5cbd7',
    authDomain: 'to-do-app-5cbd7.firebaseapp.com',
    storageBucket: 'to-do-app-5cbd7.firebasestorage.app',
    measurementId: 'G-DG2X8F4ZCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ1V4Qtrkuhllzt_SAiUtWNASCiKBgu_0',
    appId: '1:610530270497:android:25962a6178c2dab5e07260',
    messagingSenderId: '610530270497',
    projectId: 'to-do-app-5cbd7',
    storageBucket: 'to-do-app-5cbd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDADimJ37GvJl4kZi4ixcFd-Ri3dOxyqPo',
    appId: '1:610530270497:ios:f2def9c7a82ad9b6e07260',
    messagingSenderId: '610530270497',
    projectId: 'to-do-app-5cbd7',
    storageBucket: 'to-do-app-5cbd7.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDADimJ37GvJl4kZi4ixcFd-Ri3dOxyqPo',
    appId: '1:610530270497:ios:f2def9c7a82ad9b6e07260',
    messagingSenderId: '610530270497',
    projectId: 'to-do-app-5cbd7',
    storageBucket: 'to-do-app-5cbd7.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArKWnJldG8mJMXADIReb2tG6KVs-M8Gbg',
    appId: '1:610530270497:web:4562ff1e6bd9f57de07260',
    messagingSenderId: '610530270497',
    projectId: 'to-do-app-5cbd7',
    authDomain: 'to-do-app-5cbd7.firebaseapp.com',
    storageBucket: 'to-do-app-5cbd7.firebasestorage.app',
    measurementId: 'G-TZ18C7CYNH',
  );
}
